[package]
name = "httpget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
to-socket-addrs= "0.2"
once_cell = "1.4.0"
url = "^2.2.2"
